# Generated by Django 4.2.5 on 2023-10-09 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название привычки')),
                ('place', models.CharField(max_length=255, verbose_name='Место действия')),
                ('time', models.TimeField(verbose_name='Время действия')),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('is_pleasurable', models.BooleanField(default=True, verbose_name='Признак полезной привычки')),
                ('periodic', models.PositiveIntegerField(default=1, verbose_name='Периодичность в днях')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вознаграждение')),
                ('execution_time', models.TimeField(blank=True, null=True, verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=True, verbose_name='Признак публичности')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.habit', verbose_name='Связанная привычка')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
